# Generated by Django 3.0.8 on 2020-07-28 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='idea_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='motivation_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
